name: Deploy Seguro

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Substituir chaves
        run: |
          sed -i "s/GOOGLE_MAPS_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" *.html
          sed -i "s/SUA_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g" *.js
          sed -i "s/SEU_PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g" *.js

      - name: Validar substituições
        run: |
          if grep -q "GOOGLE_MAPS_API_KEY" *.html; then
            echo "❌ Chave do Maps não substituída!"; exit 1
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
