name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Dispara o workflow quando há push no branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Substituir a chave de API no arquivo index.html (se necessário)
      - name: Replace API key in index.html
        run: |
          sed -i "s/YOUR_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" index.html

      # 3. Fazer o deploy no branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Diretório com os arquivos do site
          force_orphan: true  # Cria um branch gh-pages limpo (sem histórico)
