name: Deploy Seguro

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Substituir chaves nos arquivos
        run: |
          sed -i "s/GOOGLE_MAPS_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" admin.js admin.html index.html
          sed -i "s/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g" admin.js admin.html index.html
          sed -i "s/FIREBASE_PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g" admin.js admin.html index.html
          sed -i "s/SEU_MESSAGING_SENDER_ID/000000000000/g" admin.js
          sed -i "s/SEU_APP_ID/1:000000000000:web:000000000000/g" admin.js
          sed -i "s/SEU_AUTH_DOMAIN/${{ secrets.FIREBASE_PROJECT_ID }}.firebaseapp.com/g" admin.js

      - name: Validar substituições
        run: |
          if grep -q -E "GOOGLE_MAPS_API_KEY|FIREBASE_API_KEY|FIREBASE_PROJECT_ID" admin.js admin.html index.html; then
            echo "❌ Chaves principais não substituídas!"; exit 1
          else
            echo "✅ Todas as chaves principais foram substituídas com sucesso."
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
