name: Deploy Seguro

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Substituir chaves nos arquivos
        run: |
          # Substitui a Google Maps key nos HTMLs que usam o script
          sed -i "s/GOOGLE_MAPS_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" admin.html index.html

          # Substitui chaves do Firebase em arquivos que contêm placeholders (inclui script.js)
          sed -i "s/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g" admin.js admin.html index.html script.js
          sed -i "s/FIREBASE_PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g" admin.js admin.html index.html script.js

          # Ajuste específico para admin.js: transforma import.meta.env.FIREBASE_API_KEY em uma string JS válida
          sed -i 's/import.meta.env.FIREBASE_API_KEY/"${{ secrets.FIREBASE_API_KEY }}"/g' admin.js

          # Substituições estáticas antigas (mantidas)
          sed -i "s/SEU_MESSAGING_SENDER_ID/000000000000/g" admin.js
          sed -i "s/SEU_APP_ID/1:000000000000:web:000000000000/g" admin.js
          sed -i "s/SEU_AUTH_DOMAIN/${{ secrets.FIREBASE_PROJECT_ID }}.firebaseapp.com/g" admin.js

      - name: Validar substituições
        run: |
          if grep -q -E "GOOGLE_MAPS_API_KEY|FIREBASE_API_KEY|FIREBASE_PROJECT_ID" admin.js admin.html index.html script.js; then
            echo "❌ Chaves principais não substituídas!"; exit 1
          else
            echo "✅ Todas as chaves principais foram substituídas com sucesso."
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
